program: src/fundusClassif/scripts/train.py
name: sweep_project_DRGrading_V1
method: grid
metric:
  goal: maximize
  name: Validation Quadratic Kappa
parameters:
  lr:
    values : [0.001,0.0005,0.0001,0.00005, 0.00001, 0.00005]
  data_augmentation_type:
    values: ["None", "light"]
  preprocessing:
    values: ["sarki", "absent", "autobalance", "clahe_lab", "clahe_rgb","clahe_max_green_gsc","seoud"]

command:
  - python
  - ${program}
  - ${args}