program: src/fundusClassif/scripts/train.py
name: sweep_project_DRGrading
method: bayes
metric:
  goal: maximize
  name: Validation Quadratic Kappa
parameters:
  lr:
    min: 0.00001
    max: 0.1
  optimizer:
    values: ["AdamP", "AdamW"]
  ema : 
    values: [0, 1]
  #decay:
  #  min: 0.9
  #  max: 0.9999
  swa :
    values: [0, 1]
  #swa_lrs:
  #  min: 0.00001
   # max: 0.01
  as_regression :
    values: [0, 1]
  data_augmentation_type:
    values: ["light", "medium", "heavy", "superheavy"]
  preprocessing:
    values: ["absent", "autobalance", "clahe_lab", "clahe_rgb", "seoud", "sarki", "graham_meth1", "graham_meth2", "clahe_max_green_gsc"]
  mixup: 
    values: [0, 1]
  mixup_alpha: 
      min: 0.0
      max: 1.0
  cutmix_alpha: 
      min: 0.0
      max: 1.0
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 81
  #dropout:
  #  min: 0.0
  #  max: 0.5

command:
  - python
  - ${program}
  - ${args}