
define: &img_shape [512, 512]

logger:
  project: Grading-DiabeticRetinopathy-Comparisons-V3

datasets:
  eyepacs: /home/florian/Documents/donnees_medicales/eyepacs/
  aptos: /home/florian/Documents/donnees_medicales/aptos/
  idrid: /home/florian/Documents/donnees_medicales/IDRID/B. Disease Grading/ 
  ddr: /home/florian/Documents/donnees_medicales/DDR-dataset/DR_grading/

data:
  img_size: *img_shape
  batch_size: 96 #64
  valid_size: 0.2 
  num_workers: 8
  use_cache: True
  cache_option: disk  #disk or memory
  data_augmentation_type: heavy #heavy  or heavyarticle
  drop_last: True

data_preprocessing:
  name: absent

model:
  architecture: mobilenetv4_conv_medium.e500_r256_in1k
  num_classes: 5 
  pretrained: True #True
  img_size: *img_shape 

training:
  lr: 0.00003
  as_regression: False #true
  optimizer:
    name: AdamW #or AdamW
    betas: [.9, .999] # [.9, .999]
    weight_decay: 0.0005
 

trainer:
  accumulate_grad_batches: 1 #4
  accelerator: gpu #gpu
  deterministic: False #false
  devices: [0] 
  max_epochs: 45 #200
  precision: 16-mixed #16-mixed
  check_val_every_n_epoch: 1 #1
  num_sanity_val_steps: 2 #2
  fast_dev_run: False #false
  
