program: src/fundusClassif/scripts/train.py
name: sweep_project_DRGrading_v1
method: grid
metric:
  goal: maximize
  name: Validation Quadratic Kappa
parameters:
  lr:
    values : [0.00001, 0.00005, 0.0001, 0.0005, 0.001]
  data_augmentation_type:
    values: ["light", "None"]
  preprocessing:
    values: ["absent", "autobalance", "clahe_lab", "clahe_rgb","clahe_max_green_gsc","seoud", "sarki"] # "graham_meth1", "graham_meth2"

command:
  - python
  - ${program}
  - ${args}